############################################################
#
#    Exception in destructor
#
############################################################

class MyClass(object):
    # if the DTOR tries to throw, the exception is converted to a 
    # simple error message on stderr and the DTOR exits immediately 
    def __del__(self):
        raise Exception("Oops")
        print "Bar: Bye"


def f():
    x = MyClass()   # DTOR called after this line
    
try:
    f()
    raise Exception("only get here if exceptions ignored in DTOR")
except Exception, e:
    print e